<?php
declare(strict_types=1);

/**
 * Campaign tasks + promotion calendar — shared data layer for tasks.php and
 * promotion.php. Both read/write the single `campaign_tasks` table.
 *
 * Areas: logistica | parcerias | promocao | producao
 * Promotion calendar = rows with a non-null post_date (usually area=promocao),
 * grouped by the 4 comms phases from the planning meeting.
 */

const EDV_CAMPAIGN_AREAS = [
    'promocao'  => 'Promoção',
    'parcerias' => 'Parcerias',
    'logistica' => 'Logística',
    'producao'  => 'Produção',
];

const EDV_CAMPAIGN_STATUSES = [
    'todo'  => 'A fazer',
    'doing' => 'Em curso',
    'done'  => 'Feito',
];

function edv_campaign_now_sql(): string
{
    return date('Y-m-d H:i:s');
}

function edv_campaign_ensure_schema(PDO $pdo): void
{
    $driver = (string) $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
    if ($driver === 'mysql') {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS campaign_tasks (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                area VARCHAR(20) NOT NULL DEFAULT 'producao',
                title VARCHAR(255) NOT NULL,
                details TEXT NULL,
                owner VARCHAR(120) NULL,
                status VARCHAR(12) NOT NULL DEFAULT 'todo',
                due_date DATE NULL,
                post_date DATE NULL,
                phase TINYINT UNSIGNED NULL,
                channel VARCHAR(120) NULL,
                source VARCHAR(40) NOT NULL DEFAULT 'manual',
                wa_sent_at DATETIME NULL,
                sort_order INT NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                KEY idx_area (area),
                KEY idx_post_date (post_date)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
        );
    } elseif ($driver === 'pgsql') {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS campaign_tasks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                area VARCHAR(20) NOT NULL DEFAULT 'producao',
                title VARCHAR(255) NOT NULL,
                details TEXT NULL,
                owner VARCHAR(120) NULL,
                status VARCHAR(12) NOT NULL DEFAULT 'todo',
                due_date DATE NULL,
                post_date DATE NULL,
                phase SMALLINT NULL,
                channel VARCHAR(120) NULL,
                source VARCHAR(40) NOT NULL DEFAULT 'manual',
                wa_sent_at TIMESTAMP WITHOUT TIME ZONE NULL,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
            )"
        );
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_campaign_area ON campaign_tasks (area)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_campaign_post_date ON campaign_tasks (post_date)");
    } else {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS campaign_tasks (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                area TEXT NOT NULL DEFAULT 'producao',
                title TEXT NOT NULL,
                details TEXT NULL,
                owner TEXT NULL,
                status TEXT NOT NULL DEFAULT 'todo',
                due_date TEXT NULL,
                post_date TEXT NULL,
                phase INTEGER NULL,
                channel TEXT NULL,
                source TEXT NOT NULL DEFAULT 'manual',
                wa_sent_at TEXT NULL,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )"
        );
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_campaign_area ON campaign_tasks (area)");
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_campaign_post_date ON campaign_tasks (post_date)");
    }
}

function edv_campaign_area_label(string $area): string
{
    return EDV_CAMPAIGN_AREAS[$area] ?? ucfirst($area);
}

function edv_campaign_status_label(string $status): string
{
    return EDV_CAMPAIGN_STATUSES[$status] ?? $status;
}

/** Seed tasks + promotion phases from the 27-Jun planning meeting (idempotent). */
function edv_campaign_seed_from_meeting(PDO $pdo): void
{
    $count = (int) $pdo->query("SELECT COUNT(*) FROM campaign_tasks WHERE source = 'meeting'")->fetchColumn();
    if ($count > 0) {
        return;
    }

    // [area, title, owner, status, due_date, post_date, phase, channel, details]
    $rows = [
        // Promoção
        ['promocao', 'Publicar anúncio Early Bird (25€) + grupo da 1ª edição', 'Carolina', 'doing', '2026-06-09', null, null, 'Instagram', 'Comunicar no grupo WhatsApp da 1ª edição (após automação de códigos pronta).'],
        // Promotion calendar — 4 phases
        ['promocao', 'Fase 1 — Conteúdo informativo + data e local', '', 'doing', null, '2026-06-07', 1, 'Instagram/Facebook', 'Educar: Ecstatic Dance é saudável e acessível, não só para muito espirituais. Anunciar data (27 jun) e local. DJ/facilitadores ainda não obrigatórios.'],
        ['promocao', 'Fase 2 — Facilitadores + imagem do evento', '', 'todo', null, '2026-06-13', 2, 'IG/FB/Viral Agenda', 'Anunciar Alessia (círculo+cacau), Rodrigo (integração), Bernardo (DJ). Publicar imagem do evento em Facebook, Viral Agenda e sistema próprio.'],
        ['promocao', 'Fase 3 — Promoção intensa', '', 'todo', null, '2026-06-20', 3, 'Todas + presencial', 'Partilhar em novos locais, deslocação a Viseu, manter evento ativo. Push Early Bird 25€ / regresso 20€.'],
        ['promocao', 'Fase 4 — Semana do evento + semana zero', '', 'todo', null, '2026-06-24', 4, 'Produção', 'Foco na produção. Iniciar "semana zero" da próxima edição para ter já data no fim.'],
        // Parcerias
        ['parcerias', 'Criar grupo WhatsApp de facilitadores + pedir bios em falta', 'Carolina', 'todo', '2026-06-10', null, null, null, 'Arquivo de contactos de DJs/facilitadores; pedir bio a quem ainda não enviou.'],
        ['parcerias', 'Criar grupo de coordenação facilitadores/staff', 'Carolina', 'doing', null, null, null, null, 'Detalhes internos e logística. Grupo do evento (Bernardo, Alessia, Rodrigo) já existe.'],
        ['parcerias', 'Alessia + Rodrigo — transporte (Coimbra) e facilitação', '', 'todo', null, null, null, null, 'Alessia: círculo + cacau, pediu suporte. Rodrigo: integração e suporte.'],
        ['parcerias', 'Proposta à Câmara: indoor 50–200 + outdoor', 'Daniel', 'todo', null, null, null, null, 'Pedido de espaço indoor com estrutura (som, logística). Orfeão de Viseu como hipótese (verificar disponibilidade). Quinta serve outdoor.'],
        ['parcerias', 'Partilha de lucros André & Manu (adiada)', '', 'todo', null, null, null, null, '25% da faturação (após custos base) — adiada por prematura antes de 27 jun.'],
        // Logística
        ['logistica', 'Confirmar capacidade: máx 20 pessoas (site diz 60)', 'Daniel', 'todo', '2026-06-13', null, null, null, 'Decisão: o espaço atual comporta no máximo 20 pessoas. Corrigir capacity no /admin → Eventos.'],
        ['logistica', 'Catering Nua e Crua confirmado', 'Carolina', 'done', null, null, null, null, 'Parceria continua; possível levar comida para outros espaços em futuras edições.'],
        ['logistica', 'Andreia — contribuição 5€ uso de cozinha/fogão (cacau)', '', 'todo', null, null, null, null, 'Contribuição simbólica para preparar cacau durante o evento.'],
        // Produção
        ['producao', 'Upload da transcrição da reunião para o sistema/blog', 'Daniel', 'doing', '2026-06-09', null, null, null, 'Subir transcrição e configurar integrações site ↔ plataforma de eventos.'],
        ['producao', 'Integrações site ↔ Atman We Are Here', 'Daniel', 'doing', null, null, null, null, 'Plataforma central, sincronizada com o site oficial (info aparece nos dois sistemas).'],
        ['producao', 'Automação n8n: códigos promocionais por email', 'Daniel', 'doing', '2026-06-13', null, null, null, 'Códigos únicos (uso único) gerados no /admin → Códigos e enviados automaticamente por email. O sistema de códigos já existe no admin.'],
    ];

    $stmt = $pdo->prepare(
        'INSERT INTO campaign_tasks (area, title, owner, status, due_date, post_date, phase, channel, details, source, sort_order, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
    );
    $now = edv_campaign_now_sql();
    foreach ($rows as $i => $r) {
        $stmt->execute([
            $r[0],
            mb_substr($r[1], 0, 255),
            $r[2] !== '' ? $r[2] : null,
            $r[3],
            $r[4],
            $r[5],
            $r[6],
            $r[7],
            $r[8] !== '' ? $r[8] : null,
            'meeting',
            $i,
            $now,
            $now,
        ]);
    }
}

/**
 * Calendário de promoção da edição #02 (27 jun 2026), idempotente.
 * Posts datados (post_date) + tarefas de preparação/ação (due_date).
 * Editáveis/removíveis no /admin → Promoção. Marcadas source='promo_jun26'
 * para não voltarem a ser semeadas.
 */
function edv_campaign_seed_promo_schedule(PDO $pdo): void
{
    $count = (int) $pdo->query("SELECT COUNT(*) FROM campaign_tasks WHERE source = 'promo_jun26'")->fetchColumn();
    if ($count > 0) {
        return;
    }

    // [area, title, owner, status, due_date, post_date, phase, channel, details]
    $rows = [
        // —— Ações de preparação (amanhã, 17 jun) ——
        ['promocao', 'Carolina envia todos os códigos promocionais', 'Carolina', 'todo', '2026-06-17', null, 3, 'Email', 'Disparar os códigos da comunidade (1ª edição / regresso) por email via /admin → Códigos. Fazer 1 envio de teste primeiro.'],
        ['promocao', 'Promover em todos os sites/plataformas + construir lista de locais', 'Daniel', 'todo', '2026-06-17', null, 3, 'Vários', 'Submeter o evento em agendas/grupos relevantes e construir a lista em /admin → Promoção → Locais de promoção (marcar onde já foi publicado por edição).'],
        ['promocao', 'Preparar conteúdo — post "O que é Ecstatic Dance"', 'Carolina', 'todo', '2026-06-17', null, 3, null, 'Carol prepara o post educativo até dia 17 (publica a 18). Tom: saudável, acessível, sóbrio, descalços — não só para "muito espirituais".'],

        // —— Posts datados ——
        ['promocao', 'Post — Alessia (facilitação: círculo + cacau)', null, 'doing', null, '2026-06-16', 2, 'Instagram/Facebook', 'Apresentar a Alessia: círculo de abertura + cerimónia de cacau. Foto + bio curta.'],
        ['promocao', 'Post — Rodrigo (integração)', null, 'todo', null, '2026-06-17', 2, 'Instagram/Facebook', 'Apresentar o Rodrigo: espaço de integração após a dança. Foto + bio curta.'],
        ['promocao', 'Post — "O que é Ecstatic Dance" (genérico)', 'Carolina', 'todo', null, '2026-06-18', 3, 'Instagram/Facebook', 'Post educativo preparado pela Carol. Desmistificar: dança consciente, sóbria, descalços, acessível a todos.'],
        ['promocao', 'Post — "Uma semana para o evento"', null, 'todo', null, '2026-06-20', 3, 'Todos os canais', 'Contagem: falta 1 semana (27/6). Reforço de bilhetes. Early-bird terminou → standard 30€, regresso 20€.'],
        ['promocao', 'Post — logística prática (local, horário, o que trazer)', null, 'todo', null, '2026-06-22', 3, 'Instagram/Facebook', 'PROPOSTA. Nua e Crua, Viseu · portas 15:30 · dança 16:00–19:00. Trazer roupa confortável e garrafa de água; dança descalça e sóbria.'],
        ['promocao', 'Post — "Faltam 3 dias" + recontacto da comunidade', null, 'todo', null, '2026-06-24', 4, 'WhatsApp + IG stories', 'PROPOSTA. Lembrete + mensagem direta à comunidade da 1ª edição (via /admin → Participantes).'],
        ['promocao', 'Post — "Amanhã!" lembrete final', null, 'todo', null, '2026-06-26', 4, 'IG stories + WhatsApp + FB', 'PROPOSTA. Últimos bilhetes + detalhes de chegada (morada, horário, estacionamento).'],
        ['promocao', 'Story — "É hoje" + boas-vindas', null, 'todo', null, '2026-06-27', 4, 'Instagram stories', 'PROPOSTA. Story de manhã no dia do evento + acolhimento à chegada.'],
        ['promocao', 'Pós-evento — agradecimento + teaser próxima edição', null, 'todo', null, '2026-06-28', 4, 'Instagram/Facebook', 'PROPOSTA. Obrigado + foto + abrir "semana zero" da próxima edição (já com data). Liga à Fase 4.'],
    ];

    $stmt = $pdo->prepare(
        'INSERT INTO campaign_tasks (area, title, owner, status, due_date, post_date, phase, channel, details, source, sort_order, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
    );
    $now = edv_campaign_now_sql();
    foreach ($rows as $i => $r) {
        $stmt->execute([
            $r[0],
            mb_substr($r[1], 0, 255),
            $r[2],
            $r[3],
            $r[4],
            $r[5],
            $r[6],
            $r[7],
            $r[8] !== '' ? $r[8] : null,
            'promo_jun26',
            100 + $i,
            $now,
            $now,
        ]);
    }
}

/**
 * Remove os posts cortados pela equipa (19, 21, 23, 25 jun) do calendário #02.
 * Chave estável source+post_date → idempotente (no-op depois de removidos).
 */
function edv_campaign_prune_cut_promo_posts(PDO $pdo): void
{
    $cut = ['2026-06-19', '2026-06-21', '2026-06-23', '2026-06-25'];
    $in = implode(',', array_fill(0, count($cut), '?'));
    $exists = $pdo->prepare(
        "SELECT 1 FROM campaign_tasks WHERE source = 'promo_jun26' AND post_date IN ($in) LIMIT 1"
    );
    $exists->execute($cut);
    if ($exists->fetchColumn() === false) {
        return;
    }
    $pdo->prepare(
        "DELETE FROM campaign_tasks WHERE source = 'promo_jun26' AND post_date IN ($in)"
    )->execute($cut);
}

/**
 * Insere tarefas extra ad-hoc (idempotente por source+título). Para acrescentar
 * tarefas ao calendário #02 já semeado, sem reabrir o seed principal.
 */
function edv_campaign_ensure_extra_tasks(PDO $pdo): void
{
    // [area, title, owner, status, due_date, post_date, phase, channel, details]
    $tasks = [
        ['producao', 'Daniel — atualizar página de vendas: preço correto + programa', 'Daniel', 'todo', '2026-06-17', null, null, '/links', 'Pôr o /links com o preço correto (mín. 30€, regresso 20€) e o programa disponível. Via /admin → Eventos ou UPDATE na BD de produção.'],
    ];

    $check = $pdo->prepare("SELECT 1 FROM campaign_tasks WHERE source = 'promo_jun26' AND title = ? LIMIT 1");
    $ins = $pdo->prepare(
        'INSERT INTO campaign_tasks (area, title, owner, status, due_date, post_date, phase, channel, details, source, sort_order, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
    );
    $now = edv_campaign_now_sql();
    foreach ($tasks as $i => $t) {
        $check->execute([$t[1]]);
        if ($check->fetchColumn() !== false) {
            continue;
        }
        $ins->execute([
            $t[0], mb_substr($t[1], 0, 255), $t[2], $t[3], $t[4], $t[5], $t[6],
            $t[7] !== '' ? $t[7] : null, $t[8] !== '' ? $t[8] : null,
            'promo_jun26', 200 + $i, $now, $now,
        ]);
    }
}

/** @return array<int,array<string,mixed>> */
function edv_campaign_all(PDO $pdo): array
{
    return $pdo->query(
        'SELECT * FROM campaign_tasks ORDER BY
            CASE status WHEN \'done\' THEN 2 ELSE 1 END,
            sort_order ASC, id ASC'
    )->fetchAll();
}

function edv_campaign_create(PDO $pdo, array $d): void
{
    $now = edv_campaign_now_sql();
    $stmt = $pdo->prepare(
        'INSERT INTO campaign_tasks (area, title, owner, status, due_date, post_date, phase, channel, details, source, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
    );
    $stmt->execute([
        $d['area'], mb_substr($d['title'], 0, 255), $d['owner'], $d['status'],
        $d['due_date'], $d['post_date'], $d['phase'], $d['channel'], $d['details'],
        'manual', $now, $now,
    ]);
}

function edv_campaign_update(PDO $pdo, int $id, array $d): void
{
    $stmt = $pdo->prepare(
        'UPDATE campaign_tasks SET area=?, title=?, owner=?, status=?, due_date=?, post_date=?, phase=?, channel=?, details=?, updated_at=? WHERE id=?'
    );
    $stmt->execute([
        $d['area'], mb_substr($d['title'], 0, 255), $d['owner'], $d['status'],
        $d['due_date'], $d['post_date'], $d['phase'], $d['channel'], $d['details'],
        edv_campaign_now_sql(), $id,
    ]);
}

function edv_campaign_set_status(PDO $pdo, int $id, string $status): void
{
    $stmt = $pdo->prepare('UPDATE campaign_tasks SET status=?, updated_at=? WHERE id=?');
    $stmt->execute([$status, edv_campaign_now_sql(), $id]);
}

function edv_campaign_delete(PDO $pdo, int $id): void
{
    $pdo->prepare('DELETE FROM campaign_tasks WHERE id=?')->execute([$id]);
}

function edv_campaign_mark_wa_sent(PDO $pdo, int $id): void
{
    $stmt = $pdo->prepare('UPDATE campaign_tasks SET wa_sent_at=?, updated_at=? WHERE id=?');
    $now = edv_campaign_now_sql();
    $stmt->execute([$now, $now, $id]);
}

function edv_campaign_get(PDO $pdo, int $id): ?array
{
    $stmt = $pdo->prepare('SELECT * FROM campaign_tasks WHERE id=? LIMIT 1');
    $stmt->execute([$id]);
    $row = $stmt->fetch();
    return is_array($row) ? $row : null;
}

/** Parse ?ym=YYYY-MM -> [year, month]; default to the event month (Jun 2026). */
function edv_campaign_calendar_ym(string $raw): array
{
    if (preg_match('/^(\d{4})-(\d{2})$/', $raw, $m)) {
        $y = (int) $m[1];
        $mo = (int) $m[2];
        if ($mo >= 1 && $mo <= 12 && $y >= 2024 && $y <= 2100) {
            return [$y, $mo];
        }
    }
    return [2026, 6];
}

/**
 * Render a month calendar grid. $byDate is keyed 'Y-m-d' => list of
 * ['label' => string, 'cls' => string].
 */
function edv_campaign_month_calendar(array $byDate, int $year, int $month): string
{
    $months = [1 => 'Janeiro', 2 => 'Fevereiro', 3 => 'Março', 4 => 'Abril', 5 => 'Maio', 6 => 'Junho',
        7 => 'Julho', 8 => 'Agosto', 9 => 'Setembro', 10 => 'Outubro', 11 => 'Novembro', 12 => 'Dezembro'];
    $first = mktime(0, 0, 0, $month, 1, $year);
    $daysIn = (int) date('t', $first);
    $startDow = (int) date('N', $first); // 1=Mon .. 7=Sun
    $todayYmd = date('Y-m-d');
    $name = ($months[$month] ?? '') . ' ' . $year;

    $prevY = $month === 1 ? $year - 1 : $year;
    $prevM = $month === 1 ? 12 : $month - 1;
    $nextY = $month === 12 ? $year + 1 : $year;
    $nextM = $month === 12 ? 1 : $month + 1;
    $esc = static fn (string $s): string => htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');

    $out = '<div class="cal"><div class="cal-head">'
        . '<a class="cal-nav" href="?ym=' . sprintf('%04d-%02d', $prevY, $prevM) . '">‹</a>'
        . '<span>' . $esc($name) . '</span>'
        . '<a class="cal-nav" href="?ym=' . sprintf('%04d-%02d', $nextY, $nextM) . '">›</a>'
        . '</div><div class="cal-grid">';
    foreach (['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'] as $d) {
        $out .= '<div class="cal-dow">' . $d . '</div>';
    }
    for ($i = 1; $i < $startDow; $i++) {
        $out .= '<div class="cal-cell cal-empty"></div>';
    }
    for ($day = 1; $day <= $daysIn; $day++) {
        $ymd = sprintf('%04d-%02d-%02d', $year, $month, $day);
        $out .= '<div class="cal-cell' . ($ymd === $todayYmd ? ' is-today' : '') . '">';
        $out .= '<div class="cal-day">' . $day . '</div>';
        foreach ($byDate[$ymd] ?? [] as $it) {
            $label = (string) ($it['label'] ?? '');
            $out .= '<div class="cal-chip ' . $esc((string) ($it['cls'] ?? '')) . '" title="' . $esc($label) . '">' . $esc($label) . '</div>';
        }
        $out .= '</div>';
    }
    return $out . '</div></div>';
}

/* ============================================================
   WhatsApp digest + two-way bot — shared logic
   Used by server/api/tasks-digest.php (scheduled morning post),
   server/api/tasks-command.php (inbound commands) and the public
   follow-up board server/api/tarefas.php.
   ============================================================ */

/**
 * Build the morning task digest (open / overdue / due-soon) as text + counts.
 * The footer line (total + follow-up link) is left to the caller.
 *
 * @return array{date:string, open:int, overdue:int, today:int, soon:int, no_owner:int, text:string}
 */
function edv_campaign_digest(PDO $pdo, ?string $today = null): array
{
    $today = $today ?: date('Y-m-d');
    $soonLimit = date('Y-m-d', strtotime($today . ' +3 days'));

    $rows = $pdo->query(
        "SELECT * FROM campaign_tasks WHERE status <> 'done'
         ORDER BY (CASE WHEN due_date IS NULL THEN 1 ELSE 0 END), due_date ASC, sort_order ASC"
    )->fetchAll();

    $overdue = $dueToday = $soon = $noOwner = [];
    foreach ($rows as $r) {
        $d = (string) ($r['due_date'] ?? '');
        if ($d !== '' && $d < $today) {
            $overdue[] = $r;
        } elseif ($d === $today && $d !== '') {
            $dueToday[] = $r;
        } elseif ($d !== '' && $d <= $soonLimit) {
            $soon[] = $r;
        }
        if (empty($r['owner'])) {
            $noOwner[] = $r;
        }
    }

    $fmt = static function (array $r): string {
        $s = '• ' . (string) $r['title'];
        if (!empty($r['owner'])) {
            $s .= ' (' . (string) $r['owner'] . ')';
        }
        if (!empty($r['due_date'])) {
            $s .= ' — ' . substr((string) $r['due_date'], 0, 10);
        }
        return $s;
    };

    $lines = ['☀️ *Tarefas ED Viseu* — ' . $today];
    if ($overdue !== []) {
        $lines[] = '';
        $lines[] = '⚠️ *Atrasadas*';
        foreach ($overdue as $r) {
            $lines[] = $fmt($r);
        }
    }
    if ($dueToday !== []) {
        $lines[] = '';
        $lines[] = '📌 *Hoje*';
        foreach ($dueToday as $r) {
            $lines[] = $fmt($r);
        }
    }
    if ($soon !== []) {
        $lines[] = '';
        $lines[] = '🔜 *Próximos 3 dias*';
        foreach ($soon as $r) {
            $lines[] = $fmt($r);
        }
    }
    if ($overdue === [] && $dueToday === [] && $soon === []) {
        $lines[] = '';
        $lines[] = 'Sem tarefas com prazo iminente. 🙌';
    }
    if ($noOwner !== []) {
        $lines[] = '';
        $lines[] = '🙋 *Sem responsável* (' . count($noOwner) . ') — atribuir';
    }

    return [
        'date'     => $today,
        'open'     => count($rows),
        'overdue'  => count($overdue),
        'today'    => count($dueToday),
        'soon'     => count($soon),
        'no_owner' => count($noOwner),
        'text'     => implode("\n", $lines),
    ];
}

/** Map a PT label/key (promoção, parcerias, logística, produção…) to an area key, or null. */
function edv_campaign_area_key(string $raw): ?string
{
    $raw = mb_strtolower(trim($raw));
    $map = [
        'promocao' => 'promocao', 'promoção' => 'promocao', 'promo' => 'promocao',
        'parcerias' => 'parcerias', 'parceria' => 'parcerias',
        'logistica' => 'logistica', 'logística' => 'logistica',
        'producao' => 'producao', 'produção' => 'producao', 'prod' => 'producao',
    ];
    if (isset($map[$raw])) {
        return $map[$raw];
    }
    return isset(EDV_CAMPAIGN_AREAS[$raw]) ? $raw : null;
}

/** Open tasks grouped by area, each line prefixed with #id — for the WhatsApp bot. */
function edv_campaign_open_list_text(PDO $pdo): string
{
    $rows = $pdo->query(
        "SELECT * FROM campaign_tasks WHERE status <> 'done'
         ORDER BY (CASE WHEN due_date IS NULL THEN 1 ELSE 0 END), due_date ASC, sort_order ASC"
    )->fetchAll();
    if ($rows === []) {
        return 'Sem tarefas abertas. 🙌';
    }
    $byArea = [];
    foreach ($rows as $r) {
        $byArea[(string) $r['area']][] = $r;
    }
    $lines = ['📋 *Tarefas abertas ED Viseu*'];
    foreach (EDV_CAMPAIGN_AREAS as $key => $label) {
        if (empty($byArea[$key])) {
            continue;
        }
        $lines[] = '';
        $lines[] = '*' . $label . '*';
        foreach ($byArea[$key] as $r) {
            $s = '#' . (int) $r['id'] . ' ' . (string) $r['title'];
            if (!empty($r['owner'])) {
                $s .= ' (' . (string) $r['owner'] . ')';
            }
            if (!empty($r['due_date'])) {
                $s .= ' — ' . substr((string) $r['due_date'], 0, 10);
            }
            if (($r['status'] ?? '') === 'doing') {
                $s .= ' ⏳';
            }
            $lines[] = $s;
        }
    }
    $lines[] = '';
    $lines[] = '✅ _feito <nº>_   ➕ _nova <área>: <título>_';
    return implode("\n", $lines);
}

function edv_campaign_help_text(): string
{
    return implode("\n", [
        '🤖 *Bot ED Viseu* — comandos:',
        '• *tarefas* — lista tarefas abertas (com nº)',
        '• *feito <nº>* — marca tarefa como concluída',
        '• *nova <área>: <título>* — cria tarefa',
        '   áreas: promoção · parcerias · logística · produção',
        '• *ajuda* — mostra isto',
    ]);
}

/**
 * Interpret a WhatsApp message and act on it. Returns the reply text, or null
 * when the message isn't a recognised command (so the bot stays silent on normal chat).
 */
function edv_campaign_handle_command(PDO $pdo, string $text): ?string
{
    $text = trim($text);
    if ($text === '') {
        return null;
    }
    $words = preg_split('/\s+/', $text) ?: [];
    $first = mb_strtolower($words[0] ?? '');

    if (in_array($first, ['ajuda', 'help', 'comandos', 'menu'], true)) {
        return edv_campaign_help_text();
    }
    if (in_array($first, ['tarefas', 'tasks', 'lista', 'status'], true)) {
        return edv_campaign_open_list_text($pdo);
    }
    if (in_array($first, ['feito', 'done', 'concluir', 'concluido', 'concluído'], true)) {
        if (!preg_match('/(\d+)/', $text, $m)) {
            return 'Indica o número da tarefa. Ex.: *feito 3* (vê os números com *tarefas*).';
        }
        $id = (int) $m[1];
        $task = edv_campaign_get($pdo, $id);
        if ($task === null) {
            return "Não encontrei a tarefa #$id. Vê os números com *tarefas*.";
        }
        if (($task['status'] ?? '') === 'done') {
            return "A tarefa #$id já estava concluída: " . (string) $task['title'];
        }
        edv_campaign_set_status($pdo, $id, 'done');
        return "✅ Concluída #$id: " . (string) $task['title'];
    }
    if (in_array($first, ['nova', 'novo', 'add'], true)) {
        $rest = trim(mb_substr($text, mb_strlen($words[0])));
        $area = 'producao';
        $title = $rest;
        if (preg_match('/^([^:]{1,20}):\s*(.+)$/u', $rest, $m)) {
            $maybe = edv_campaign_area_key(trim($m[1]));
            if ($maybe !== null) {
                $area = $maybe;
                $title = trim($m[2]);
            }
        }
        $title = trim($title);
        if ($title === '') {
            return 'Formato: *nova <área>: <título>* (áreas: promoção, parcerias, logística, produção).';
        }
        edv_campaign_create($pdo, [
            'area' => $area, 'title' => $title, 'owner' => null, 'status' => 'todo',
            'due_date' => null, 'post_date' => null, 'phase' => null, 'channel' => null,
            'details' => 'Criada via WhatsApp.',
        ]);
        return '➕ Criada em *' . edv_campaign_area_label($area) . '*: ' . $title;
    }

    return null;
}
