<?php
declare(strict_types=1);

/**
 * Locais de promoção — lista mestre de sítios onde divulgamos cada edição
 * (agendas culturais, grupos de Facebook/WhatsApp/Telegram, Instagram, cartazes…).
 *
 * A lista persiste entre edições (tabela `promo_places`). Para cada edição
 * marcamos quando publicámos em cada local (tabela `promo_place_posts`,
 * uma linha por par local↔evento). Usada por server/admin/promotion.php.
 */

const EDV_PROMO_PLACE_TYPES = [
    'agenda'    => 'Agenda cultural',
    'fb_grupo'  => 'Grupo Facebook',
    'fb_pagina' => 'Página Facebook',
    'whatsapp'  => 'Grupo WhatsApp',
    'telegram'  => 'Grupo Telegram',
    'instagram' => 'Instagram',
    'cartaz'    => 'Cartaz / presencial',
    'outro'     => 'Outro',
];

function edv_promo_places_now_sql(): string
{
    return date('Y-m-d H:i:s');
}

function edv_promo_places_ensure_schema(PDO $pdo): void
{
    $driver = (string) $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
    if ($driver === 'mysql') {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS promo_places (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(160) NOT NULL,
                type VARCHAR(20) NOT NULL DEFAULT 'outro',
                url VARCHAR(500) NULL,
                notes TEXT NULL,
                is_active TINYINT(1) NOT NULL DEFAULT 1,
                sort_order INT NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
        );
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS promo_place_posts (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                place_id BIGINT UNSIGNED NOT NULL,
                event_id BIGINT UNSIGNED NOT NULL,
                posted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                notes VARCHAR(255) NULL,
                UNIQUE KEY uq_place_event (place_id, event_id),
                KEY idx_event (event_id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
        );
    } elseif ($driver === 'pgsql') {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS promo_places (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(160) NOT NULL,
                type VARCHAR(20) NOT NULL DEFAULT 'outro',
                url VARCHAR(500) NULL,
                notes TEXT NULL,
                is_active SMALLINT NOT NULL DEFAULT 1,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
            )"
        );
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS promo_place_posts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                place_id BIGINT NOT NULL,
                event_id BIGINT NOT NULL,
                posted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                notes VARCHAR(255) NULL,
                CONSTRAINT uq_place_event UNIQUE (place_id, event_id)
            )"
        );
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_promo_post_event ON promo_place_posts (event_id)");
    } else {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS promo_places (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                type TEXT NOT NULL DEFAULT 'outro',
                url TEXT NULL,
                notes TEXT NULL,
                is_active INTEGER NOT NULL DEFAULT 1,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )"
        );
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS promo_place_posts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                place_id INTEGER NOT NULL,
                event_id INTEGER NOT NULL,
                posted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                notes TEXT NULL,
                UNIQUE (place_id, event_id)
            )"
        );
        $pdo->exec("CREATE INDEX IF NOT EXISTS idx_promo_post_event ON promo_place_posts (event_id)");
    }
}

function edv_promo_place_type_label(string $type): string
{
    return EDV_PROMO_PLACE_TYPES[$type] ?? ucfirst($type);
}

/** Starter list of channels (idempotent). URLs reais ficam por preencher onde não confirmadas. */
function edv_promo_places_seed(PDO $pdo): void
{
    $count = (int) $pdo->query('SELECT COUNT(*) FROM promo_places')->fetchColumn();
    if ($count > 0) {
        return;
    }

    // [name, type, url, notes]
    $rows = [
        ['Viral Agenda', 'agenda', 'https://www.viralagenda.com', 'Submeter o evento na agenda cultural (alcance regional).'],
        ['Agenda Cultural de Viseu', 'agenda', '', 'Agenda da Câmara / cidade — confirmar o canal de submissão.'],
        ['Instagram @ecstaticdanceviseu', 'instagram', '', 'Feed + stories. Conta oficial.'],
        ['Facebook — Página Ecstatic Dance Viseu', 'fb_pagina', '', 'Publicar evento + posts das 4 fases.'],
        ['Facebook — grupos de dança/consciência (Viseu/Centro)', 'fb_grupo', '', 'Partilhar em grupos locais de dança, bem-estar e eventos.'],
        ['WhatsApp — grupo da 1ª edição', 'whatsapp', '', 'Comunidade que já dançou connosco (com código de regresso).'],
        ['WhatsApp — facilitadores / staff', 'whatsapp', '', 'Grupo de coordenação interna.'],
        ['Telegram — comunidade ecstatic dance', 'telegram', '', 'Canais/grupos de dança e eventos conscientes.'],
        ['Cartazes — Viseu (cafés, estúdios de yoga, lojas bio)', 'cartaz', '', 'Distribuição física em pontos de passagem da comunidade.'],
    ];

    $stmt = $pdo->prepare(
        'INSERT INTO promo_places (name, type, url, notes, is_active, sort_order, created_at)
         VALUES (?, ?, ?, ?, 1, ?, ?)'
    );
    $now = edv_promo_places_now_sql();
    foreach ($rows as $i => $r) {
        $stmt->execute([
            mb_substr($r[0], 0, 160),
            $r[1],
            $r[2] !== '' ? $r[2] : null,
            $r[3] !== '' ? $r[3] : null,
            $i,
            $now,
        ]);
    }
}

/** @return array<int,array<string,mixed>> All places (optionally only active). */
function edv_promo_places_all(PDO $pdo, bool $onlyActive = false): array
{
    $sql = 'SELECT * FROM promo_places';
    if ($onlyActive) {
        $sql .= ' WHERE is_active = 1';
    }
    $sql .= ' ORDER BY is_active DESC, sort_order ASC, name ASC';
    return $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC) ?: [];
}

function edv_promo_place_create(PDO $pdo, string $name, string $type, string $url, string $notes): void
{
    if (!isset(EDV_PROMO_PLACE_TYPES[$type])) {
        $type = 'outro';
    }
    $maxOrder = (int) $pdo->query('SELECT COALESCE(MAX(sort_order), 0) FROM promo_places')->fetchColumn();
    $stmt = $pdo->prepare(
        'INSERT INTO promo_places (name, type, url, notes, is_active, sort_order, created_at)
         VALUES (?, ?, ?, ?, 1, ?, ?)'
    );
    $stmt->execute([
        mb_substr($name, 0, 160),
        $type,
        $url !== '' ? mb_substr($url, 0, 500) : null,
        $notes !== '' ? $notes : null,
        $maxOrder + 1,
        edv_promo_places_now_sql(),
    ]);
}

function edv_promo_place_update(PDO $pdo, int $id, string $name, string $type, string $url, string $notes): void
{
    if (!isset(EDV_PROMO_PLACE_TYPES[$type])) {
        $type = 'outro';
    }
    $stmt = $pdo->prepare('UPDATE promo_places SET name=?, type=?, url=?, notes=? WHERE id=?');
    $stmt->execute([
        mb_substr($name, 0, 160),
        $type,
        $url !== '' ? mb_substr($url, 0, 500) : null,
        $notes !== '' ? $notes : null,
        $id,
    ]);
}

function edv_promo_place_toggle_active(PDO $pdo, int $id): void
{
    $cur = $pdo->prepare('SELECT is_active FROM promo_places WHERE id=?');
    $cur->execute([$id]);
    $val = $cur->fetchColumn();
    if ($val === false) {
        return;
    }
    $new = ((int) $val) === 1 ? 0 : 1;
    $pdo->prepare('UPDATE promo_places SET is_active=? WHERE id=?')->execute([$new, $id]);
}

function edv_promo_place_delete(PDO $pdo, int $id): void
{
    $pdo->prepare('DELETE FROM promo_place_posts WHERE place_id=?')->execute([$id]);
    $pdo->prepare('DELETE FROM promo_places WHERE id=?')->execute([$id]);
}

/**
 * Toggle "publicado neste local para esta edição". Returns true if now marked,
 * false if unmarked.
 */
function edv_promo_place_toggle_posted(PDO $pdo, int $placeId, int $eventId): bool
{
    $q = $pdo->prepare('SELECT id FROM promo_place_posts WHERE place_id=? AND event_id=?');
    $q->execute([$placeId, $eventId]);
    $existing = $q->fetchColumn();
    if ($existing !== false) {
        $pdo->prepare('DELETE FROM promo_place_posts WHERE id=?')->execute([(int) $existing]);
        return false;
    }
    $pdo->prepare('INSERT INTO promo_place_posts (place_id, event_id, posted_at) VALUES (?, ?, ?)')
        ->execute([$placeId, $eventId, edv_promo_places_now_sql()]);
    return true;
}

/** @return array<int,string> place_id => posted_at (Y-m-d H:i:s) for one event. */
function edv_promo_place_posts_for_event(PDO $pdo, int $eventId): array
{
    $q = $pdo->prepare('SELECT place_id, posted_at FROM promo_place_posts WHERE event_id=?');
    $q->execute([$eventId]);
    $map = [];
    foreach ($q->fetchAll(PDO::FETCH_ASSOC) as $r) {
        $map[(int) $r['place_id']] = (string) $r['posted_at'];
    }
    return $map;
}
