-- ============================================================
-- Ecstatic Dance Viseu — PostgreSQL schema
-- Usado quando DB_DRIVER = pgsql (inclui Supabase)
-- ============================================================

CREATE TABLE IF NOT EXISTS events (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  date        DATE NOT NULL,
  time_start  TIME DEFAULT '16:00:00',
  time_end    TIME DEFAULT '19:00:00',
  doors_open  TIME DEFAULT '15:30:00',
  location    VARCHAR(255) DEFAULT 'Viseu',
  type        VARCHAR(16) NOT NULL DEFAULT 'paid' CHECK (type IN ('free', 'paid')),
  capacity    INTEGER NOT NULL DEFAULT 60 CHECK (capacity >= 0),
  min_price   NUMERIC(8,2) NOT NULL DEFAULT 25.00,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_date_active ON events (date, is_active);

CREATE TABLE IF NOT EXISTS tickets (
  id                CHAR(36) PRIMARY KEY,
  event_id          INTEGER NOT NULL REFERENCES events(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  name              VARCHAR(255) NOT NULL,
  email             VARCHAR(255) NOT NULL,
  phone             VARCHAR(30) NOT NULL,
  amount_paid       NUMERIC(8,2) NOT NULL DEFAULT 0.00,
  payment_status    VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'free')),
  stripe_session_id VARCHAR(255) DEFAULT NULL,
  checked_in        BOOLEAN NOT NULL DEFAULT FALSE,
  checked_in_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
  paid_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
  created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_status ON tickets (event_id, payment_status);
CREATE INDEX IF NOT EXISTS idx_email ON tickets (email);
CREATE INDEX IF NOT EXISTS idx_stripe_session ON tickets (stripe_session_id);
CREATE INDEX IF NOT EXISTS idx_checked_in ON tickets (checked_in);

CREATE TABLE IF NOT EXISTS link_registrations (
  id                 CHAR(36) PRIMARY KEY,
  payment_ref        VARCHAR(40) NOT NULL UNIQUE,
  event_slug         VARCHAR(64) NOT NULL DEFAULT 'edv-2026-05-23',
  name               VARCHAR(255) NOT NULL,
  email              VARCHAR(255) NOT NULL,
  phone              VARCHAR(40) NOT NULL,
  ticket_euros       NUMERIC(8,2) NOT NULL,
  dinner_note        VARCHAR(64) NOT NULL DEFAULT '',
  total_euros        NUMERIC(8,2) NOT NULL,
  payment_method     VARCHAR(20) NOT NULL CHECK (payment_method IN ('mbway', 'transfer', 'revolut')),
  heard_from         VARCHAR(32) NOT NULL,
  heard_other        VARCHAR(255) DEFAULT NULL,
  step1_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  step2_type         VARCHAR(20) DEFAULT NULL CHECK (step2_type IS NULL OR step2_type IN ('upload', 'email_later')),
  proof_relpath      VARCHAR(512) DEFAULT NULL,
  proof_mime         VARCHAR(120) DEFAULT NULL,
  step2_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
  created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_link_email ON link_registrations (email);
CREATE INDEX IF NOT EXISTS idx_link_step1 ON link_registrations (step1_at);
